name: Generating Variable Fonts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        font-source:
          - NotoSans-MM.glyphs
          - NotoSansDisplay-MM.glyphs
          - NotoSans-ItalicMM.glyphs
          - NotoSansDisplay-ItalicMM.glyphs
          - NotoSerif-MM.glyphs
          - NotoSerifDisplay-MM.glyphs
          - NotoSerif-ItalicMM.glyphs
          - NotoSerifDisplay-ItalicMM.glyphs
          - NotoSansMono-MM.glyphs
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Pull main repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build ${{ matrix.font-source }}
      run: |
        fontmake -g sources/${{ matrix.font-source}} -o variable
    - name: Store fonts
      uses: actions/upload-artifact@v1
      with:
        name: variable-fonts
        path: variable_ttf

  fontbakery:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        font-family:
          - NotoSans
          - NotoSansDisplay
          - NotoSans-Italic
          - NotoSansDisplay-Italic
          - NotoSerif
          - NotoSerifDisplay
          - NotoSerif-Italic
          - NotoSerifDisplay-Italic
          - NotoSansMono
    steps:
    - name: Pull main repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fontbakery
    - name: Download fonts
      uses: actions/download-artifact@v2
      id: download
      with:
        name: variable-fonts
        path: builds/variable_ttf
    - name: List files
      run: |
        find builds
    - name: Create Fontbakery report directory
      run: |
        mkdir -p reports/fontbakery
    - name: Fontbakery checks ${{ matrix.font-family }}
      uses: f-actions/font-bakery@v1
      with:
        subcmd: "check-opentype"
        args: "-x monospace -x glyf_nested_components -x fontbakery_version -x dsig --loglevel WARN --ghmarkdown reports/fontbakery/${{ matrix.font-family }}.md"
        path: "builds/variable_ttf/${{ matrix.font-family }}-VF.ttf"
    - name: Store Fontbakery reports
      uses: actions/upload-artifact@v1
      with:
        name: reports-fontbakery
        path: reports/fontbakery

  fontdiffenator:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        font-family:
          - NotoSans
          - NotoSansDisplay
          - NotoSans-Italic
          - NotoSansDisplay-Italic
          - NotoSerif
          - NotoSerifDisplay
          - NotoSerif-Italic
          - NotoSerifDisplay-Italic
          - NotoSansMono
        weight: [100, 400, 700, 900]
        width: [62.5, 100]
    steps:
      - name: Pull main repository
        uses: actions/checkout@v2
      - name: Setup
        run: |
          pip install fontdiffenator
      - name: Download fonts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: variable-fonts
          path: builds/variable_ttf
      - name: Download previous fonts
        run: |
          mkdir -p previous
          curl -o previous/${{ matrix.font-family }}-VF.ttf https://raw.githubusercontent.com/googlefonts/noto-fonts/main/unhinted/variable-ttf/${{ matrix.font-family }}-VF.ttf
      - name: Run fontdiffenator
        run: |
          mkdir -p reports/fontdiffenator/${{ matrix.font-family }}-weight${{ matrix.weight }}-width${{ matrix.width }}
          fontdiffenator previous/${{ matrix.font-family }}-VF.ttf builds/variable_ttf/${{ matrix.font-family }}-VF.ttf -i "wght=${{ matrix.weight }}, wdth=${{ matrix.width }}" --html -r images > ${{ matrix.font-family }}-weight${{ matrix.weight }}-width${{ matrix.width }}.html
          mv images ${{ matrix.font-family }}-weight${{ matrix.weight }}-width${{ matrix.width }}.html reports/fontdiffenator/${{ matrix.font-family }}-weight${{ matrix.weight }}-width${{ matrix.width }}
      - name: Store FontDiffenator reports
        uses: actions/upload-artifact@v1
        with:
          name: fontdiffenator-reports
          path: reports/fontdiffenator
